-- Setup local de MySQL para prode-api.
-- El script completo para crear la base, el usuario de MySQL, las tablas y los datos iniciales
-- esta en docs/setupydatosbd.sql.
--
-- Ejecutar docs/setupydatosbd.sql completo en MySQL Workbench con un usuario administrador,
-- por ejemplo root.
